# Generated by Django 3.2.5 on 2022-07-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userrecipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utensils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utensil_name', models.CharField(max_length=100, null=True)),
                ('utensil_id', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
