# Generated by Django 3.2.5 on 2022-07-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='time',
            new_name='cooking_time',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='name',
            new_name='recipe_name',
        ),
        migrations.RenameField(
            model_name='userrecipes',
            old_name='time',
            new_name='cooking_time',
        ),
        migrations.RenameField(
            model_name='userrecipes',
            old_name='name',
            new_name='recipe_name',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='userrecipes',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipes',
            name='recipe_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userrecipes',
            name='recipe_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
