# Generated by Django 3.2.5 on 2022-07-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220720_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, null=True)),
                ('recipe_id', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
