# Generated by Django 3.2.5 on 2022-07-21 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_process_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_steps',
            name='recipe_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.recipes'),
        ),
    ]
