# Generated by Django 3.2.5 on 2022-07-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20220720_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_steps',
            name='Quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
