# Generated by Django 3.2.5 on 2022-07-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_process_steps_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_steps',
            name='unit',
            field=models.CharField(choices=[('ml', 'ml'), ('kg', 'kg')], max_length=200, null=True),
        ),
    ]
