# Generated by Django 3.2.5 on 2022-07-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_process_steps_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process_steps',
            old_name='unit',
            new_name='Quantity_unit',
        ),
        migrations.AddField(
            model_name='process_steps',
            name='temperature_unit',
            field=models.CharField(choices=[('°C', '°C'), ('°F', '°F')], max_length=200, null=True),
        ),
    ]
