# Generated by Django 3.2.5 on 2022-07-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_recipes_number_of_serves'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_steps',
            name='process',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
