# Generated by Django 3.2.5 on 2022-07-21 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_process_steps_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='keyword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.recipes'),
        ),
        migrations.AlterField(
            model_name='process_steps',
            name='Quantity_unit',
            field=models.CharField(choices=[('ml', 'ml'), ('kg', 'kg'), ('gram', 'gram'), ('undefined', 'undefined')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='process_steps',
            name='temperature_unit',
            field=models.CharField(choices=[('°C', '°C'), ('°F', '°F'), ('undefined', 'undefined')], max_length=200, null=True),
        ),
    ]
