# Generated by Django 3.2.5 on 2022-07-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20220721_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='keyword',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='recipe_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.recipes'),
        ),
    ]
