# Generated by Django 3.2.5 on 2022-08-07 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_model_password'),
        ('dashboard', '0020_alter_recipes_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(null=True)),
                ('recipe_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.recipes')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user_model')),
            ],
        ),
    ]
