# Generated by Django 3.2.5 on 2022-08-12 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_list_made_by_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='list_made_by_user',
        ),
    ]
