# Generated by Django 3.2.5 on 2022-08-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='password',
        ),
    ]
